//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penjualan_Buku
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTransaksi
    {
        public int IdDetail { get; set; }
        public Nullable<int> IdTransaksi { get; set; }
        public Nullable<int> IdBuku { get; set; }
        public Nullable<int> Jumlah { get; set; }
        public Nullable<decimal> HargaSaatTransaksi { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    
        public virtual Buku Buku { get; set; }
        public virtual Transaksi Transaksi { get; set; }
    }
}
