//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penjualan_Buku
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaksi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaksi()
        {
            this.DetailTransaksis = new HashSet<DetailTransaksi>();
        }
    
        public int IdTransaksi { get; set; }
        public Nullable<int> IdPelanggan { get; set; }
        public Nullable<System.DateTime> Tanggal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailTransaksi> DetailTransaksis { get; set; }
        public virtual Pelanggan Pelanggan { get; set; }
    }
}
